### PR TITLE
 Fix sha256, bump build number, update maintainers, rerender

### PR DESCRIPTION
**Pull request by dbast**
Last merged version to master was not published. Update to fix that.

### CODE REVIEW

**Comment by dbast** [comment]
bemeurer is now lovesegfault, as indicated by the linter in https://github.com/conda-forge/beautysh-feedstock/pull/3

**Comment by dbast** [comment]
Ok. Builds now. Ready to merge :)

**Comment by lovesegfault** [comment]
Only @bollwyvl can merge this, @dbast. I left the conda-forge org because of the tremendous amount of noise it created on my Travis panel.

**Comment by bollwyvl** [comment]
Sorry, not at my keyboard at the moment. Will address this evening. Thanks
for the ping!

**Comment by bollwyvl** [comment]
Just to be a tiny bit picky, setuptools is a dependency of pip, so not
strictly necessary in host, but otherwise looks good!

**Comment by dbast** [comment]
Ok, right. Updated once again :)

**Comment by bollwyvl** [comment]
Thanks @dbast! Will monitor [the build](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=37279) and do... something if it doesn't work again.

**Comment by bollwyvl** [comment]
Everything looks on the up-and-up!

**Comment by dbast** [comment]
Thanks!

**Pull request merged**
